export { default as Layout } from '../layout/Layout'
export { default as SignIn } from '../pages/SignIn'
export { default as SignUp } from '../pages/SignUp'
export { default as ProductDetailContainer } from '../pages/ProductDetailContainer'
export { default as ProductDetail } from '../pages/ProductDetail'
export { default as Mangas } from '../pages/Mangas'
export {default as Home } from '../pages/Home'